### ISSUE TITLE
Missing release asset for 1.7.0

### ISSUE THREAD

**Issue by hisaac** [a7ex/xcresultparser#41]
Hi @a7ex. I just noticed that the [1.7.0 release](https://github.com/a7ex/xcresultparser/releases/tag/1.7.0) doesn't have the release asset attached.

**Comment by a7ex** [comment]
Hi Isaac, I cannot notarize the binary, because Xcode 16 is still in beta.
I can not build with Xcode 15, because the package defines "swift 6.0"
So I can not provide a binary for 1.7.0.
That is also the reason, that I didn't create a new version for brew.

You will need to build yourself a binary from source.

**Comment by hisaac** [comment]
Ah gotcha, that makes sense. I'll close this then, thank you.

**Comment by a7ex** [comment]
Hi Isaac,
xcresultparser is now at version 1.7.1 and reverted back to Swift 5.10 which builds with Xcode 15.
You can now download the notarized binary here: https://github.com/a7ex/xcresultparser/releases/tag/1.7.1
